START TRANSACTION;
DELETE c FROM daily_plan_ftod c JOIN daily_plan_period p ON c.period_id=p.period_id WHERE p.plan_date='2026-06-20' AND p.created_by='pg_migration';
DELETE c FROM daily_plan_dpd c JOIN daily_plan_period p ON c.period_id=p.period_id WHERE p.plan_date='2026-06-20' AND p.created_by='pg_migration';
DELETE c FROM daily_plan_npa c JOIN daily_plan_period p ON c.period_id=p.period_id WHERE p.plan_date='2026-06-20' AND p.created_by='pg_migration';
DELETE c FROM daily_plan_fy_non_start c JOIN daily_plan_period p ON c.period_id=p.period_id WHERE p.plan_date='2026-06-20' AND p.created_by='pg_migration';
DELETE c FROM daily_plan_kyc c JOIN daily_plan_period p ON c.period_id=p.period_id WHERE p.plan_date='2026-06-20' AND p.created_by='pg_migration';
DELETE c FROM daily_plan_disb c JOIN daily_plan_period p ON c.period_id=p.period_id WHERE p.plan_date='2026-06-20' AND p.created_by='pg_migration';
DELETE FROM daily_plan_period WHERE plan_date='2026-06-20' AND created_by='pg_migration';
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7686, 63, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7687, 50, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7688, 23, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7689, 46, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7690, 55, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7691, 45, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7692, 48, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7693, 47, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7694, 10, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7695, 97, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7696, 54, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7697, 93, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7698, 92, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7699, 5, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7700, 58, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7701, 4, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7702, 94, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7703, 56, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7704, 2, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7705, 91, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7706, 96, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7707, 43, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7708, 44, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7709, 57, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7710, 49, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7711, 52, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7712, 51, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_period (period_id,branch_id,plan_date,submission_type_id,dm_employee_id,created_at,updated_at,created_by,updated_by) VALUES (7713, 53, '2026-06-20', 1, NULL, '2026-06-20 10:42:54', '2026-06-20 10:42:54', 'pg_migration', NULL);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7686, 29, 6);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7687, 20, 10);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7688, 24, 7);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7689, 21, 6);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7690, 33, 10);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7691, 17, 4);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7692, 62, 15);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7693, 0, 10);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7694, 68, 10);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7695, 45, 20);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7696, 28, 10);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7697, 33, 10);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7698, 60, 15);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7699, 87, 20);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7700, 40, 15);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7701, 22, 7);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7702, 77, 25);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7703, 29, 7);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7704, 55, 15);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7705, 41, 15);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7706, 7, 1);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7707, 28, 5);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7708, 12, 3);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7709, 15, 6);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7710, 31, 10);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7711, 41, 8);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7712, 72, 50);
INSERT INTO daily_plan_ftod (period_id,actual_count,plan_count) VALUES (7713, 14, 5);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7686, 2, 14, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7686, 3, 13, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7686, 6, 1, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7687, 2, 16, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7687, 3, 0, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7687, 6, 19, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7688, 2, 9, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7688, 3, 10, 2);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7688, 6, 3, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7689, 2, 4, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7689, 3, 8, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7689, 6, 5, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7690, 2, 10, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7690, 3, 9, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7690, 6, 23, 2);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7691, 2, 8, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7691, 3, 13, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7691, 6, 13, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7692, 2, 6, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7692, 3, 28, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7692, 6, 11, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7693, 2, 0, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7693, 3, 0, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7693, 6, 0, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7694, 2, 22, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7694, 3, 22, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7694, 6, 12, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7695, 2, 5, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7695, 3, 6, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7695, 6, 0, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7696, 2, 2, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7696, 3, 4, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7696, 6, 8, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7697, 2, 1, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7697, 3, 3, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7697, 6, 1, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7698, 2, 10, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7698, 3, 15, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7698, 6, 8, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7699, 2, 30, 2);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7699, 3, 29, 2);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7699, 6, 17, 2);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7700, 2, 0, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7700, 3, 1, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7700, 6, 0, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7701, 2, 9, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7701, 3, 13, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7701, 6, 2, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7702, 2, 15, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7702, 3, 24, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7702, 6, 15, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7703, 2, 1, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7703, 3, 1, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7703, 6, 1, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7704, 2, 11, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7704, 3, 8, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7704, 6, 25, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7705, 2, 2, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7705, 3, 3, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7705, 6, 5, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7706, 2, 2, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7706, 3, 2, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7706, 6, 0, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7707, 2, 0, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7707, 3, 3, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7707, 6, 5, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7708, 2, 6, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7708, 3, 13, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7708, 6, 6, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7709, 2, 33, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7709, 3, 5, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7709, 6, 8, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7710, 2, 10, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7710, 3, 18, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7710, 6, 21, 2);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7711, 2, 7, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7711, 3, 9, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7711, 6, 11, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7712, 2, 11, 1);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7712, 3, 22, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7712, 6, 17, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7713, 2, 7, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7713, 3, 11, 0);
INSERT INTO daily_plan_dpd (period_id,bucket_id,actual_count,plan_count) VALUES (7713, 6, 7, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7686, 1, 6);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7686, 2, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7687, 1, 10);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7687, 2, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7688, 1, 10);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7688, 2, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7689, 1, 10);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7689, 2, 3);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7690, 1, 2);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7690, 2, 3);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7691, 1, 7);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7691, 2, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7692, 1, 8);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7692, 2, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7693, 1, 10);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7693, 2, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7694, 1, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7694, 2, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7695, 1, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7695, 2, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7696, 1, 3);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7696, 2, 2);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7697, 1, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7697, 2, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7698, 1, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7698, 2, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7699, 1, 8);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7699, 2, 2);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7700, 1, 6);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7700, 2, 2);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7701, 1, 1);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7701, 2, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7702, 1, 1);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7702, 2, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7703, 1, 6);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7703, 2, 2);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7704, 1, 2);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7704, 2, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7705, 1, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7705, 2, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7706, 1, 1);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7706, 2, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7707, 1, 6);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7707, 2, 5);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7708, 1, 15);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7708, 2, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7709, 1, 5);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7709, 2, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7710, 1, 6);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7710, 2, 0);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7711, 1, 5);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7711, 2, 2);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7712, 1, 7);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7712, 2, 4);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7713, 1, 6);
INSERT INTO daily_plan_npa (period_id,action_id,count) VALUES (7713, 2, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7686, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7687, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7688, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7689, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7690, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7691, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7692, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7693, 0, 2);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7694, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7695, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7696, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7697, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7698, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7699, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7700, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7701, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7702, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7703, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7704, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7705, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7706, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7707, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7708, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7709, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7710, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7711, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7712, 0, 0);
INSERT INTO daily_plan_fy_non_start (period_id,actual_count,plan_count) VALUES (7713, 0, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7686, 1, 5);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7686, 2, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7686, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7687, 1, 12);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7687, 2, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7687, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7688, 1, 8);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7688, 2, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7688, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7689, 1, 2);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7689, 2, 2);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7689, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7690, 1, 8);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7690, 2, 4);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7690, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7691, 1, 5);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7691, 2, 2);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7691, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7692, 1, 15);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7692, 2, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7692, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7693, 1, 4);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7693, 2, 4);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7693, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7694, 1, 15);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7694, 2, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7694, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7695, 1, 10);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7695, 2, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7695, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7696, 1, 3);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7696, 2, 3);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7696, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7697, 1, 10);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7697, 2, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7697, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7698, 1, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7698, 2, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7698, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7699, 1, 5);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7699, 2, 6);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7699, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7700, 1, 8);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7700, 2, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7700, 3, 1);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7701, 1, 10);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7701, 2, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7701, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7702, 1, 5);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7702, 2, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7702, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7703, 1, 7);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7703, 2, 2);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7703, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7704, 1, 15);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7704, 2, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7704, 3, 2);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7705, 1, 5);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7705, 2, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7705, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7706, 1, 10);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7706, 2, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7706, 3, 1);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7707, 1, 5);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7707, 2, 5);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7707, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7708, 1, 7);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7708, 2, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7708, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7709, 1, 3);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7709, 2, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7709, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7710, 1, 10);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7710, 2, 5);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7710, 3, 2);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7711, 1, 5);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7711, 2, 5);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7711, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7712, 1, 5);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7712, 2, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7712, 3, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7713, 1, 6);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7713, 2, 0);
INSERT INTO daily_plan_kyc (period_id,product_type_id,kyc_count) VALUES (7713, 3, 0);
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7686, 1, 6, '390000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7686, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7686, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7687, 1, 2, '160000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7687, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7687, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7688, 1, 8, '480000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7688, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7688, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7689, 1, 2, '200000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7689, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7689, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7690, 1, 4, '320000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7690, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7690, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7691, 1, 6, '580000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7691, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7691, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7692, 1, 4, '240000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7692, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7692, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7693, 1, 4, '240000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7693, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7693, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7694, 1, 1, '100000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7694, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7694, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7695, 1, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7695, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7695, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7696, 1, 2, '140000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7696, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7696, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7697, 1, 1, '60000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7697, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7697, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7698, 1, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7698, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7698, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7699, 1, 6, '320000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7699, 2, 6, '320000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7699, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7700, 1, 1, '100000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7700, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7700, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7701, 1, 3, '180000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7701, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7701, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7702, 1, 1, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7702, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7702, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7703, 1, 3, '210000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7703, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7703, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7704, 1, 3, '180000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7704, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7704, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7705, 1, 1, '50000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7705, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7705, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7706, 1, 1, '50000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7706, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7706, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7707, 1, 3, '180000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7707, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7707, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7708, 1, 6, '600000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7708, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7708, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7709, 1, 3, '180000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7709, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7709, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7710, 1, 3, '240000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7710, 2, 1, '80000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7710, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7711, 1, 2, '160000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7711, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7711, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7712, 1, 5, '400000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7712, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7712, 3, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7713, 1, 1, '80000.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7713, 2, 0, '0.00');
INSERT INTO daily_plan_disb (period_id,product_type_id,accounts,amount) VALUES (7713, 3, 0, '0.00');
COMMIT;
