"""Per-run report history for EOD and Hourly.

Each successful report generation creates a UNIQUE run folder, so multiple runs
on the same date are ALL preserved (until retention deletes them after the
3-day window) instead of the latest run overwriting the previous one:

    <data_dir>/<archive_dir>/<YYYY-MM-DD>/<HH-MM-SS[-n]>/
        <friendly report name>.xlsx        # snapshot copies, not the live files
        meta.json                          # run metadata (size, expiry, status)

The ``*_Latest.xlsx`` files in the backend dir are left untouched — they remain
the "current state" for the source/processing flow. This module only copies
snapshots into history, so Reports & Downloads can show run history while the
processing engine keeps using the latest files.

Layout is identical for both modules; only the archive dir name and the set of
report files differ (see ``_ARCHIVE_DIR`` / ``_FILES``).
"""
from __future__ import annotations

import json
import os
import re
import shutil
import time
from pathlib import Path

# module -> archive subdir under data_dir
_ARCHIVE_DIR = {
    "eod": "reports_archive",
    "hourly": "reports_archive_hourly",
    "quick": "reports_archive_quick",
    "quick_month_end": "reports_archive_qme",
    "db": "reports_archive_db",
}

# module -> {type: (source *_Latest file, friendly archived name, UI label)}
# Only USER-FACING reports are archived/shown here. Internal reports (employee,
# daily, etc.) are still generated by the engine but not surfaced in history.
_FILES = {
    "eod": {
        "output": ("EOD_Output_Latest.xlsx", "Regular Demand vs Collection.xlsx", "Regular Demand vs Collection Report"),
        "report": ("EOD_Report_Latest.xlsx", "Daily Collection Report.xlsx", "Daily Collection Report"),
    },
    # Only the generated Hourly Fast Report is surfaced in Reports & Downloads
    # (named "Hourly Report"). The detailed Hourly Collection Report stays as a
    # *_Latest file for the VBA/bundle flow but is NOT archived/listed here.
    "hourly": {
        "output": ("Hourly_Fast_Report_Latest.xlsx", "Hourly Report.xlsx", "Hourly Report"),
    },
    "quick": {
        "output": ("Quick_Report_Latest.xlsx", "Quick Hourly Report.xlsx", "Quick Hourly Report"),
    },
    "quick_month_end": {
        "output": ("EOD_Output_Latest.xlsx", "Regular Demand vs Collection.xlsx", "Regular Demand vs Collection"),
        "report": ("EOD_Report_Latest.xlsx", "EOD Report.xlsx", "EOD Report"),
        "employee": ("Quick_Month_End_Employee_Latest.xlsx", "Month-End Employee Report.xlsx", "Month-End Employee Report"),
    },
    "db": {
        "output": ("DB_Disbursement_Report_Latest.xlsx", "Disbursement Report.xlsx", "Disbursement Report"),
    },
}

# Stable UI order of report types within a run. Per-module; falls back to the
# natural key order of that module's _FILES entry.
_ORDER_MAP = {
    "eod": ["output", "report"],
    "hourly": ["output"],
    "quick": ["output"],
    "quick_month_end": ["output", "report", "employee"],
    "db": ["output"],
}


def _order(module: str) -> list:
    return _ORDER_MAP.get(module) or list(_FILES.get(module, {}).keys())


def retention_days() -> int:
    try:
        return int(os.environ.get("NLPL_RETENTION_DAYS", "3"))
    except ValueError:
        return 3


def archive_root(data_dir, module) -> Path:
    return Path(data_dir) / _ARCHIVE_DIR[module]


def _norm_date(s: str) -> str:
    """Normalise a date string to YYYY-MM-DD (accepts dd-mm-yyyy or yyyy-mm-dd)."""
    s = (s or "").strip()
    m = re.match(r"^(\d{2})-(\d{2})-(\d{4})$", s)  # dd-mm-yyyy
    if m:
        return f"{m.group(3)}-{m.group(2)}-{m.group(1)}"
    if re.match(r"^\d{4}-\d{2}-\d{2}$", s):  # already yyyy-mm-dd
        return s
    return time.strftime("%Y-%m-%d")


def _safe_token(tok: str) -> bool:
    return bool(tok) and ".." not in tok and "/" not in tok and "\\" not in tok


def _present_date(date_part: str) -> str:
    """Render a YYYY-MM-DD date as dd-mm-yyyy for filenames, matching the
    'as on DD-MM-YYYY' text printed inside the reports."""
    m = re.match(r"^(\d{4})-(\d{2})-(\d{2})$", (date_part or "").strip())
    return f"{m.group(3)}-{m.group(2)}-{m.group(1)}" if m else (date_part or "").strip()


def _safe_name_part(s: str) -> str:
    """Strip characters that are illegal in filenames; map ':' -> '-' so a time
    like '9:30 AM' becomes a valid '9-30 AM'."""
    s = (s or "").replace(":", "-")
    return "".join(c for c in s if c not in '\\/*?:"<>|').strip()


def _archived_name(module: str, type_: str, default_nice: str,
                   date_part: str, time_label: str) -> str:
    """Build the archived/download filename, embedding the report's date (and,
    for hourly, the time) so the downloaded file is self-describing.

    Falls back to the static friendly name for any report not specially named."""
    d = _present_date(date_part)
    if module == "eod" and type_ == "report" and d:
        return f"Daily Collection Report as on {d}.xlsx"
    if module == "hourly" and type_ == "output" and d:
        t = _safe_name_part(time_label)
        name = f"Hourly Report as on {d} {t}".strip()
        return f"{name}.xlsx"
    return default_nice


def _newest_mtime(directory: Path) -> float:
    newest = 0.0
    try:
        for f in directory.rglob("*"):
            if f.is_file():
                try:
                    newest = max(newest, f.stat().st_mtime)
                except OSError:
                    continue
    except OSError:
        pass
    return newest


# ---------------------------------------------------------------- snapshot ---
def _unique_run_dir(date_dir: Path) -> tuple[Path, str]:
    base = time.strftime("%H-%M-%S")
    run_id = base
    n = 2
    while (date_dir / run_id).exists():
        run_id = f"{base}-{n}"
        n += 1
    p = date_dir / run_id
    p.mkdir(parents=True, exist_ok=True)
    return p, run_id


def snapshot(data_dir, module: str, date_str: str, time_label: str = "") -> dict:
    """Copy the current *_Latest report files into a fresh run folder.

    Creates a new run only if at least one source report exists. Missing
    reports are recorded as unavailable for that run (never silently filled
    with a stale latest file)."""
    if module not in _FILES:
        return {"success": False, "error": f"unknown module '{module}'"}

    backend = Path(data_dir) / "backend"
    present = [
        (key, backend / _FILES[module][key][0], _FILES[module][key][1], _FILES[module][key][2])
        for key in _order(module)
    ]
    if not any(src.exists() for _, src, _, _ in present):
        return {"success": False, "skipped": True,
                "message": "No report files to archive yet."}

    date_part = _norm_date(date_str)
    date_dir = archive_root(data_dir, module) / date_part
    date_dir.mkdir(parents=True, exist_ok=True)
    dest, run_id = _unique_run_dir(date_dir)

    now = time.time()
    saved_at = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(now))
    expires_at = time.strftime("%Y-%m-%d %H:%M:%S",
                               time.localtime(now + retention_days() * 86400))
    hour_label = time_label.strip() if time_label else time.strftime("%I:%M %p", time.localtime(now))

    reports = {}
    for key, src, nice, label in present:
        # Archive under a date/time-stamped name so the downloaded file is
        # self-describing (e.g. "Daily Collection Report as on 18-06-2026.xlsx").
        arch_name = _archived_name(module, key, nice, date_part, hour_label)
        entry = {"label": label, "name": arch_name, "available": False, "size": None}
        if src.exists():
            try:
                shutil.copy2(src, dest / arch_name)
                entry["available"] = True
                entry["size"] = (dest / arch_name).stat().st_size
            except OSError:
                pass
        reports[key] = entry

    meta = {
        "module": module,
        "runId": run_id,
        "date": date_part,
        "label": (date_str or date_part).strip(),
        "time": hour_label,
        "savedAt": saved_at,
        "expiresAt": expires_at,
        "reports": reports,
    }
    try:
        (dest / "meta.json").write_text(json.dumps(meta), encoding="utf-8")
    except OSError:
        pass
    return {"success": True, **meta}


# ------------------------------------------------------------------- list ---
def _read_run(run_dir: Path, module: str) -> dict:
    meta = {}
    mp = run_dir / "meta.json"
    if mp.exists():
        try:
            meta = json.loads(mp.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            meta = {}

    reports, available, missing = [], [], []
    for key in _order(module):
        _src, nice, label = _FILES[module][key]
        meta_rep = (meta.get("reports") or {}).get(key, {})
        # The on-disk file uses the name recorded in meta (it embeds date/time);
        # fall back to the static friendly name for runs archived before this.
        arch_name = meta_rep.get("name") or nice
        fp = run_dir / arch_name
        exists = fp.exists()
        size = None
        if exists:
            try:
                size = fp.stat().st_size
            except OSError:
                size = meta_rep.get("size")
        reports.append({
            "type": key,
            "label": meta_rep.get("label", label),
            "name": arch_name,
            "size": size,
            "available": exists,
        })
        (available if exists else missing).append(key)

    return {
        "runId": meta.get("runId", run_dir.name),
        "date": meta.get("date", run_dir.parent.name),
        "label": meta.get("label", run_dir.parent.name),
        "time": meta.get("time", ""),
        "savedAt": meta.get("savedAt"),
        "expiresAt": meta.get("expiresAt"),
        "reports": reports,
        "available": available,
        "missing": missing,
    }


def list_history(data_dir, module) -> list:
    """Return report history grouped by date (newest first), each date holding
    all its runs (newest first). Runs past the retention window are skipped
    (retention also physically deletes them)."""
    out = []
    if module not in _ARCHIVE_DIR or module not in _FILES:
        return out  # unknown module (e.g. one with its own native history): no archive
    root = archive_root(data_dir, module)
    if not root.exists():
        return out
    cutoff = time.time() - retention_days() * 86400

    for date_dir in sorted([p for p in root.iterdir() if p.is_dir()],
                           key=lambda p: p.name, reverse=True):
        runs = []
        for run_dir in sorted([p for p in date_dir.iterdir() if p.is_dir()],
                              key=lambda p: p.name, reverse=True):
            if _newest_mtime(run_dir) < cutoff:
                continue  # expired — don't show
            runs.append(_read_run(run_dir, module))
        if not runs:
            continue
        out.append({
            "date": date_dir.name,
            "label": runs[0].get("label") or date_dir.name,
            "savedAt": runs[0].get("savedAt"),
            "runCount": len(runs),
            "runs": runs,
        })
    return out


# ------------------------------------------------------------------- file ---
def file_path(data_dir, module, date: str, run_id: str, type_: str):
    """Resolve the archived file for an exact (module, date, run, type).

    Returns None on unknown args, path-traversal attempts, or missing file."""
    if module not in _FILES or type_ not in _FILES[module]:
        return None
    if not _safe_token(run_id):
        return None
    run_dir = archive_root(data_dir, module) / _norm_date(date) / run_id
    # Resolve the real archived filename from meta.json (it embeds date/time);
    # fall back to the static friendly name for older runs.
    arch_name = _FILES[module][type_][1]
    mp = run_dir / "meta.json"
    if mp.exists():
        try:
            meta = json.loads(mp.read_text(encoding="utf-8"))
            nm = (meta.get("reports") or {}).get(type_, {}).get("name")
            if nm:
                arch_name = nm
        except (OSError, ValueError):
            pass
    p = run_dir / arch_name
    return p if p.exists() else None
