import { useState } from "react";
import {
  AlertTriangle,
  BarChart3,
  CalendarDays,
  CalendarRange,
  ExternalLink,
  FileSpreadsheet,
  LineChart,
  Wallet,
  Zap,
} from "lucide-react";
import { Button } from "../components/ui.jsx";
import EodReportsPanel from "../eod/components/ReportsPanel.jsx";
import HourlyReportsPanel from "../hourly/components/ReportsPanel.jsx";
import QuickReportsPanel from "../quick/components/ReportsPanel.jsx";
import QmeReportsPanel from "../qme/components/ReportsPanel.jsx";
import DisbReportsPanel from "../disbursement/components/ReportsPanel.jsx";
import OndateReports from "../ondate/OndateReports.jsx";

/** Info panel for modules whose reports aren't stored in a server archive. */
function InfoPanel({ title, body, openId }) {
  return (
    <div className="panel">
      <div className="panel-header">
        <div>
          <p className="eyebrow">Reports</p>
          <h2>{title}</h2>
        </div>
        {openId && (
          <Button
            size="sm"
            variant="ghost"
            icon={ExternalLink}
            onClick={() => {
              window.location.hash = openId;
            }}
          >
            Open module
          </Button>
        )}
      </div>
      <div className="empty" style={{ padding: 26 }}>
        <FileSpreadsheet size={26} />
        <p className="muted" style={{ maxWidth: 460 }}>{body}</p>
      </div>
    </div>
  );
}

// Every report-producing module + how to render its Reports & Downloads view.
const REPORT_MODULES = [
  { id: "eod", name: "EOD Module", tagline: "Demand vs Collection", icon: BarChart3, Panel: EodReportsPanel },
  { id: "hourly", name: "Hourly Module", tagline: "Hourly merging", icon: BarChart3, Panel: HourlyReportsPanel },
  { id: "quick", name: "Quick Report", tagline: "Hourly fast report", icon: Zap, Panel: QuickReportsPanel },
  { id: "quick_month_end", name: "Month-End Report", tagline: "Employee month-end", icon: CalendarRange, Panel: QmeReportsPanel },
  { id: "ondate", name: "On-Date Report", tagline: "Monthly master", icon: CalendarDays, Panel: () => <OndateReports /> },
  {
    id: "od_report",
    name: "OD Report",
    tagline: "Overdue report",
    icon: AlertTriangle,
    Panel: () => (
      <InfoPanel
        title="OD Report downloads"
        openId="od_report"
        body="The OD Report is written straight to your Downloads folder when generated (OD Report.xlsx). Open the OD Report module to generate a new one."
      />
    ),
  },
  { id: "disbursement_report", name: "Disbursement Report", tagline: "Daily disbursement", icon: Wallet, Panel: DisbReportsPanel },
  {
    id: "instant",
    name: "Instant Report",
    tagline: "Pivot summaries",
    icon: LineChart,
    Panel: () => (
      <InfoPanel
        title="Instant Report history"
        openId="instant"
        body="Instant reports are cached per date and exported to Excel from the module. Open the Instant module's Report History tab to view past dates and download them."
      />
    ),
  },
];

export default function ReportsPage() {
  const [selected, setSelected] = useState("eod");
  const current = REPORT_MODULES.find((m) => m.id === selected) || REPORT_MODULES[0];
  const Panel = current.Panel;

  return (
    <div className="reports-page-container">
      <div className="eod-head">
        <div>
          <p className="eyebrow">Archive</p>
          <h1 className="eod-title">Reports and Downloads</h1>
          <p className="muted eod-subtitle">
            Access and download historical reports generated by every operation module.
          </p>
        </div>
      </div>

      <div className="reports-layout" style={{ marginTop: 24 }}>
        <div className="date-rail">
          <div className="date-rail-label">Modules</div>
          {REPORT_MODULES.map((m) => {
            const Icon = m.icon;
            return (
              <button
                key={m.id}
                className={`date-item ${selected === m.id ? "on" : ""}`}
                onClick={() => setSelected(m.id)}
                title={m.name}
              >
                <span className="date-main" style={{ display: "flex", alignItems: "center", gap: 8 }}>
                  <Icon size={15} /> {m.name}
                </span>
                <span className="date-sub">{m.tagline}</span>
              </button>
            );
          })}
        </div>

        <div className="reports-content">
          <Panel key={selected} />
        </div>
      </div>
    </div>
  );
}
